# Generated by Django 4.0 on 2021-12-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price_per_kilo', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('shelf_life', models.TimeField(blank=True, null=True)),
                ('fridge_life', models.TimeField(blank=True, null=True)),
                ('freezable', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuisine.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('favorite', models.BooleanField()),
                ('difficulty', models.DecimalField(decimal_places=0, max_digits=1)),
                ('description', models.CharField(max_length=100)),
                ('portion_size', models.DecimalField(decimal_places=0, max_digits=3)),
                ('min_portions', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
                ('method', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuisine.author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.recipe')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.product')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.product')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.productcategory'),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('optional', models.BooleanField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.product')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.recipe')),
            ],
        ),
    ]
