# Generated by Django 4.0 on 2021-12-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStereotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('F-VEG', 'Fresh fuits, vegetables and legumes'), ('DAIRY', 'Dairy Products'), ('F-FSH', 'Fresh animal products'), ('P-VEG', 'Preserved fuits, vegetables and legumes'), ('P-FSH', 'Preserved animal products'), ('GRAIN', 'Grains and Cerals'), ('NUTS', 'Nuts and Seeds'), ('INGNT', 'Ingredients'), ('SEASN', 'Herbs and Spices'), ('EAT', 'Ready Meals'), ('BREAD', 'Breads, Pastries and Pasta'), ('SAUCE', 'Sauces and Condiments'), ('SNACK', 'Snacks, Confections and Desserts'), ('DRINK', 'Drinks')], max_length=5, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.productstereotype')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('type', models.CharField(blank=True, choices=[('STOR', 'Storage container or tupperware'), ('MEAS', 'Measuring jug'), ('SAUC', 'Saucepan or pot'), ('FRY', 'Frying pan, grill pan or wok'), ('DISH', 'Casserole or oven pan'), ('BAKE', 'Baking tray, oven pan or springform'), ('BOWL', 'Mixing bowls')], max_length=4, null=True)),
                ('shape', models.CharField(blank=True, choices=[('RECT', 'Square or rectangular'), ('CIRC', 'Circular'), ('OVAL', 'Oval or elliptical'), ('SPEC', 'Decorative mould')], max_length=4, null=True)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=1)),
                ('depth', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('heat_resistance', models.CharField(choices=[(1, 'Heatproof'), (2, 'Ovenproof'), (3, 'Flameproof')], max_length=4)),
                ('airtight', models.BooleanField()),
                ('dishwasher_safe', models.BooleanField()),
                ('microwavable', models.BooleanField()),
                ('freezer_safe', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='stereotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.productstereotype'),
        ),
    ]
