# Generated by Django 4.0 on 2021-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_productstereotype_vessel_remove_product_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productstereotype',
            name='non_gram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productstereotype',
            name='unit',
            field=models.CharField(default='gram', max_length=10),
        ),
        migrations.AddField(
            model_name='tag',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='freezable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='airtight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='dishwasher_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='freezer_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='microwavable',
            field=models.BooleanField(default=False),
        ),
    ]
