# Generated by Django 4.0 on 2021-12-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_author_verified_brand_partner_product_preferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstereotype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.productstereotype'),
        ),
    ]
