# Generated by Django 4.0 on 2021-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0006_author_biography_author_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='productstereotype',
            name='category',
            field=models.CharField(choices=[('F-VEG', 'Fresh fuits, vegetables and legumes'), ('DAIRY', 'Dairy and egg products'), ('F-MPF', 'Fresh meat, poultry and fish'), ('P-VEG', 'Preserved fuits, vegetables and legumes'), ('P-MPF', 'Preserved meat, poultry and fish'), ('GRAIN', 'Grains and Cerals'), ('NUTS', 'Nuts and Seeds'), ('INGNT', 'Ingredients'), ('SEASN', 'Herbs and Spices'), ('EAT', 'Ready Meals'), ('BREAD', 'Breads, Pastries and Pasta'), ('SAUCE', 'Sauces and Condiments'), ('SNACK', 'Snacks, Confections and Desserts'), ('DRINK', 'Drinks')], default='', max_length=5),
        ),
    ]
