# Generated by Django 4.0 on 2021-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0007_rename_brand_id_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fridge_life',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
