# Generated by Django 4.0 on 2021-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0008_alter_product_fridge_life_alter_product_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_kilo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
