# Generated by Django 4.0 on 2021-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0009_alter_product_price_per_kilo_alter_vessel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fridge_unit',
            field=models.CharField(choices=[('', 'days'), ('7*', 'weeks'), ('30*', 'months')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='self_unit',
            field=models.CharField(choices=[('', 'days'), ('7*', 'weeks'), ('30*', 'months')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='fridge_life',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
