# Generated by Django 4.0 on 2021-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0010_product_fridge_unit_product_self_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fridge_unit',
            field=models.CharField(blank=True, choices=[('', 'days'), ('7*', 'weeks'), ('30*', 'months')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='self_unit',
            field=models.CharField(blank=True, choices=[('', 'days'), ('7*', 'weeks'), ('30*', 'months')], default='', max_length=3),
        ),
    ]
