# Generated by Django 4.0 on 2021-12-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0011_alter_product_fridge_unit_alter_product_self_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='producttags',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='producttags',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipetags',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipetags',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
