# Generated by Django 4.0 on 2021-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0012_rename_product_id_ingredients_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portion_size',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
