# Generated by Django 4.0 on 2021-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0013_alter_recipe_portion_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='heat_resistance',
            field=models.CharField(choices=[(0, 'Not heat resistant'), (1, 'Heatproof'), (2, 'Ovenproof'), (3, 'Flameproof')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='shape',
            field=models.CharField(choices=[('RECT', 'Square or rectangular'), ('CIRC', 'Circular'), ('OVAL', 'Oval or elliptical'), ('SPEC', 'Decorative mould')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='type',
            field=models.CharField(choices=[('STOR', 'Storage container or tupperware'), ('MEAS', 'Measuring jug'), ('SAUC', 'Saucepan or pot'), ('FRY', 'Frying pan, grill pan or wok'), ('DISH', 'Casserole or oven pan'), ('BAKE', 'Baking tray, oven pan or springform'), ('BOWL', 'Mixing bowls')], default='', max_length=4),
        ),
    ]
