# Generated by Django 4.0 on 2021-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0015_vessel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='amount',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=3),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='heat_resistance',
            field=models.CharField(choices=[('0', 'Not heat resistant'), ('1', 'Heatproof'), ('2', 'Ovenproof'), ('3', 'Flameproof')], default='', max_length=4),
        ),
    ]
