# Generated by Django 4.0 on 2021-12-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0016_alter_vessel_amount_alter_vessel_heat_resistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetags',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetags',
            name='tag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_per_kilo',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='productstereotype',
            name='non_gram',
        ),
        migrations.RemoveField(
            model_name='productstereotype',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='cuisine.Tag'),
        ),
        migrations.AddField(
            model_name='productstereotype',
            name='density',
            field=models.DecimalField(decimal_places=3, default='1', max_digits=9),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='cuisine.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='product_tag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe_tag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='amount',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=3),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='type',
            field=models.CharField(choices=[('STOR', 'Storage container or tupperware'), ('MEAS', 'Measuring jug'), ('SAUC', 'Saucepan or pot'), ('FRY', 'Frying pan, grill pan or wok'), ('DISH', 'Casserole or oven pan'), ('BAKE', 'Baking tray, oven pan or springform'), ('BOWL', 'Mixing bowls')], default='MEAS', max_length=4),
        ),
        migrations.DeleteModel(
            name='ProductTags',
        ),
        migrations.DeleteModel(
            name='RecipeTags',
        ),
    ]
