# Generated by Django 4.0 on 2021-12-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0017_remove_recipetags_recipe_remove_recipetags_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stereotype',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='product_allergens', to='cuisine.ProductStereotype'),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=3, default='100', max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.ManyToManyField(blank=True, related_name='product_ingredients', to='cuisine.ProductStereotype'),
        ),
        migrations.AddField(
            model_name='product',
            name='trace_allergens',
            field=models.ManyToManyField(blank=True, related_name='product_allergen_traces', to='cuisine.ProductStereotype'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('m', 'grams'), ('v', 'Millilitres')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='productstereotype',
            name='allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cuisine.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cuisine.Tag'),
        ),
    ]
