# Generated by Django 4.0 on 2021-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0018_remove_product_stereotype_product_allergens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstereotype',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
