# Generated by Django 4.0 on 2021-12-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0019_alter_productstereotype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['verified', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['partner', 'brand']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['preferred', 'stereotype__category', 'stereotype', 'name', 'price']},
        ),
        migrations.AlterModelOptions(
            name='productstereotype',
            options={'ordering': ['category', 'allergen', 'parent', 'name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['favorite', 'title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['favorite', 'tag']},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['name', 'type', 'size', 'amount', 'price']},
        ),
        migrations.AddField(
            model_name='product',
            name='stereotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisine.productstereotype'),
        ),
    ]
