# Generated by Django 4.0 on 2021-12-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0020_alter_author_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-verified', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-favorite', '-partner', 'brand']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-preferred', 'stereotype__category', 'stereotype', 'name', 'price']},
        ),
        migrations.AlterModelOptions(
            name='productstereotype',
            options={'ordering': ['category', 'allergen', 'hierarchy']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-favorite', 'title', '-author__verified']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-favorite', 'tag']},
        ),
        migrations.AddField(
            model_name='brand',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productstereotype',
            name='hierarchy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
