# Generated by Django 4.0 on 2021-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0021_alter_author_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstereotype',
            name='hierarchy',
            field=models.CharField(blank=True, default='<django.db.models.fields.related.ForeignKey> > <django.db.models.fields.CharField>', max_length=100),
        ),
    ]
